### ISSUE TITLE
Error trying to push a new image to the DVC storage

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs#146]
I'm trying to upload a new GOld image with `dvc push` and I get this error:

```s
ERROR: failed to push data to the cloud - Authentication to Azure Blob Storage via SAS token failed.                                                          
Learn more about configuration settings at <https://man.dvc.org/remote/modify>: unable to connect to account for Unable to create async transport. Please check aiohttp is installed.
```

I've generated a new SAT Token but I get the same error.

I'm using dvc 2.9.4. The latest one is [2.10.1](https://github.com/iterative/dvc/releases/tag/2.10.1).

I'm going to try first to update dvc.

**Comment by josecelano** [comment]
I have updated dvc to `2.10.1 ` with `mamba`:

Install:

```s
conda install -c conda-forge mamba
mamba install -c conda-forge dvc dvc-azure
```

Update:

```s
mamba update -c conda-forge dvc dvc-azure
```

```s
dvc version
DVC version: 2.10.1 (conda)
---------------------------------
Platform: Python 3.8.2 on Linux-5.10.0-1052-oem-x86_64-with-glibc2.10
Supports:
	azure (adlfs = 2022.4.0, knack = 0.6.3, azure-identity = 1.9.0),
	webhdfs (fsspec = 2021.11.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: azureinstall
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```

But I'm still getting the same error.

**Comment by josecelano** [comment]
Running dvc push with more verbosity throws all this stuff:

```$ dvc push -v
2022-04-21 13:50:50,470 DEBUG: Preparing to transfer data from '/home/josecelano/Documents/github/Nautilus-Cyberneering/chinese-ideographs/.dvc/cache' to 'chinese-ideographs'
2022-04-21 13:50:50,470 DEBUG: Preparing to collect status from 'chinese-ideographs'
2022-04-21 13:50:50,470 DEBUG: Collecting status from 'chinese-ideographs'
2022-04-21 13:50:50,472 ERROR: failed to push data to the cloud - Authentication to Azure Blob Storage via SAS token failed.                
Learn more about configuration settings at <https://man.dvc.org/remote/modify>: unable to connect to account for Unable to create async transport. Please check aiohttp is installed.
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 30, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/core/pipeline/transport/__init__.py", line 68, in __getattr__
    from ._aiohttp import AioHttpTransport
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 32, in <module>
    import chardet  # type: ignore
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 88, in _create_pipeline
    from azure.core.pipeline.transport import AioHttpTransport
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/core/pipeline/transport/__init__.py", line 71, in __getattr__
    raise ImportError("aiohttp package is not installed")
ImportError: aiohttp package is not installed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/adlfs/spec.py", line 565, in do_connect
    self.service_client = AIOBlobServiceClient(
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/storage/blob/aio/_blob_service_client_async.py", line 115, in __init__
    super(BlobServiceClient, self).__init__(
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py", line 134, in __init__
    super(BlobServiceClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 110, in __init__
    self._config, self._pipeline = self._create_pipeline(self.credential, storage_sdk=service, **kwargs)
  File "/home/josecelano/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client_async.py", line 90, in _create_pipeline
    raise ImportError("Unable to create async transport. Please check aiohttp is installed.")
ImportError: Unable to create async transport. Please check aiohttp is installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/fs/azure.py", line 154, in fs
    return AzureBlobFileSystem(**self.fs_args)
  File "/home/josecelano/.local/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/adlfs/spec.py", line 452, in __init__
    self.do_connect()
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/adlfs/spec.py", line 588, in do_connect
    raise ValueError(f"unable to connect to account for {e}")
ValueError: unable to connect to account for Unable to create async transport. Please check aiohttp is installed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/data/transfer.py", line 154, in transfer
    status = compare_status(
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/data/status.py", line 163, in compare_status
    dest_exists, dest_missing = status(
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/data/status.py", line 135, in status
    exists.update(odb.hashes_exist(hashes, name=odb.fs_path, jobs=jobs))
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 423, in hashes_exist
    remote_size, remote_hashes = self._estimate_remote_size(hashes, name)
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 265, in _estimate_remote_size
    remote_hashes = set(iter_with_pbar(hashes))
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 254, in iter_with_pbar
    for hash_ in hashes:
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 217, in _hashes_with_limit
    for hash_ in self._list_hashes(prefix):
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 207, in _list_hashes
    for path in self._list_paths(prefix):
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/objects/db.py", line 191, in _list_paths
    yield from self.fs.find(self.fs.path.join(*parts), prefix=bool(prefix))
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 189, in find
    files = self.fs.find(with_prefix, prefix=self.path.parts(path)[-1])
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/josecelano/anaconda3/envs/dvc/lib/python3.8/site-packages/dvc/fs/azure.py", line 156, in fs
    raise AzureAuthError(
dvc.fs.azure.AzureAuthError: Authentication to Azure Blob Storage via SAS token failed.
Learn more about configuration settings at <https://man.dvc.org/remote/modify>
------------------------------------------------------------
2022-04-21 13:50:50,474 DEBUG: Analytics is enabled.
2022-04-21 13:50:50,515 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpohyn729k']'
2022-04-21 13:50:50,517 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpohyn729k']'
```
